[package]
name = "hello"
version = "0.1.0"
authors = ["vagrant"]

[dependencies]
#rust-apex = "0.1.0"
rust-apex = {git="https://github.com/cmsd2/rust-apex"}
serde_json = "0.9.0"
quick-error = "1.1.0"
rusoto = { version = "0.23", features = [] }
